/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class roompanel extends javax.swing.JPanel {

    public roompanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photo = new javax.swing.JLabel();
        roomname = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(null);

        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(photo);
        photo.setBounds(0, 0, 270, 190);

        roomname.setFont(new java.awt.Font("Candara", 1, 22)); // NOI18N
        roomname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomname.setText("nikhil");
        add(roomname);
        roomname.setBounds(0, 200, 270, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel photo;
    public javax.swing.JLabel roomname;
    // End of variables declaration//GEN-END:variables
}
