
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


public class userlogin extends javax.swing.JFrame {
        int w,h;
        public userlogin() {
        initComponents();
        setSize(500,500);
         setLocationRelativeTo(null);
         setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        bt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        nau = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LogIn");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 40, 130, 40);

        user.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        user.setOpaque(false);
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userMouseReleased(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(170, 140, 170, 40);

        bt.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        bt.setText("Submit");
        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });
        getContentPane().add(bt);
        bt.setBounds(190, 330, 130, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroundicons/Webp.net-resizeimage(15).png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 220, 50, 40);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroundicons/Webp.net-resizeimage(14).png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 140, 50, 40);

        pass.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        pass.setOpaque(false);
        getContentPane().add(pass);
        pass.setBounds(170, 220, 170, 40);

        nau.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        nau.setText("New User?");
        nau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nauActionPerformed(evt);
            }
        });
        getContentPane().add(nau);
        nau.setBounds(360, 420, 110, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroundicons/Webp.net-resizeimage(14)1.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
        String a=user.getText();
        String b=pass.getText();
        if(a.equals("")||b.equals("")) 
        {
        }
        else
        {
            try {
                
                HttpResponse<String> response=Unirest.get(GlobalData.hostname+"/userlogin")
                        .queryString("username",a)
                        .queryString("password",b)               
                        .asString();
                if(response.getBody().equals("Invalid login"))
                {
                   JOptionPane.showMessageDialog(this,"Invalid username/password");
                }
                else
                {
                    GlobalData.nameofuser=a;
                    System.out.println("~~~"+GlobalData.nameofuser);
                    new userhome().setVisible(true);
                }
            } 
            
            catch (UnirestException ex) {
                ex.printStackTrace();
            }
        }
        
               
    }//GEN-LAST:event_btActionPerformed

    private void nauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nauActionPerformed
        new Usersignup().setVisible(true);
    }//GEN-LAST:event_nauActionPerformed

    private void userMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseReleased
        
    }//GEN-LAST:event_userMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new userlogin().setVisible(true);
                    }
                }); } catch (ClassNotFoundException ex) {
                Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(userlogin.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton nau;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
